name: Build Custom Executable
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC
  #   - cron: '0 2 * * *'  # Daily at 2 AM UTC
jobs:
  custom-executable-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cdisc-org/cdisc-rules-engine
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install --no-deps -r requirements.txt
          pip install -r requirements.txt --no-cache-dir
      - name: Update CDISC standards cache
        env:
          CDISC_LIBRARY_API_KEY: ${{ secrets.CDISC_LIBRARY_API_KEY }}
        run: |
          python core.py update-cache
      - name: Build Binary
        run: |
          pyinstaller --onedir \
            --contents-directory "." \
            core.py \
            --dist ./dist/output/core-ubuntu \
            --collect-submodules pyreadstat \
            --add-data="resources/cache:resources/cache" \
            --add-data="resources/templates:resources/templates" \
            --add-data="resources/schema:resources/schema" \
            --add-data="tests/resources/datasets:tests/resources/datasets"
      - name: Prepare executable
        run: |
          cd dist/output/core-ubuntu/core
          chmod +x core
          file core  # Verify x86_64 architecture
          mv core cdisc-core-$(date +%Y%m%d)
          echo "Executable ready: $(ls cdisc-core-*)"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdisc-core-ubuntu
          path: dist/output/core-ubuntu/core

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cdisc-core-ubuntu.zip
          asset_name: cdisc-core-ubuntu.zip
          asset_content_type: application/zip
